# Generated by Django 3.2.13 on 2022-06-24 08:09

from django.db import migrations, models
import odk.models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0004_alter_xform_created_by_alter_xform_xml_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xform',
            name='xml_file',
            field=models.FileField(blank=True, help_text="XLSForm converti par <a href='https://getodk.org/xlsform/' target='_blank'>https://getodk.org/xlsform/</a>", null=True, upload_to=odk.models.xform_path, verbose_name='XML file'),
        ),
    ]
