# Generated by Django 4.0.5 on 2022-06-17 21:27

from django.db import migrations, models
import odk.models


class Migration(migrations.Migration):

    dependencies = [
        ('odk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xform',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='xform',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='xformsubmit',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='xformsubmit',
            name='modified_on',
        ),
        migrations.AddField(
            model_name='xform',
            name='model_created',
            field=models.BooleanField(default=False, verbose_name='Model created'),
        ),
        migrations.AddField(
            model_name='xformsubmit',
            name='data_loaded',
            field=models.BooleanField(default=False, verbose_name='Data loaded'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='xml_file',
            field=models.FileField(blank=True, help_text="XLSForm converted by <a href='https://getodk.org/xlsform/' target='_blank'>https://getodk.org/xlsform/</a>", null=True, upload_to=odk.models.xform_path, verbose_name='XML file'),
        ),
    ]
